window.onload = function() {
    document.write("Testing")
    document.write("<br>")
    document.write("Sebastian Sexy")
    document.write("<br>")
    document.write("I know this is annoying, having this replace the whole entire website with this text.")
    document.write("<br>")
    document.write("This will eventually get fixed right now")
    document.write("<br>")
    document.write("If you are seeing this text, the extension is working as how it should...")
    document.write("<br>")
    document.write("Once I learn GTK I'll be able to make this change the styles of page elements instead of replacing the whole page with text")
    document.write("<br>")
    document.write("To be able to turn this extension off and be able to see your websites again...")
    document.write("<br>")
    document.write("Go to chrome://extensions")
    document.write("<br>")
    document.write("Then change the slider under the GTKOnline extension to off, and reload the page")
    document.write("<br>")
    document.write("The page will then be back to normal :)")
}